Repository Gunforge/learn-go-with-tests-ko, pull requests merged in 2019-10, with the labels that each got.

#9 Config gitbook root directory
  ko-KR/.gitbook.yaml
Labels: enhancement

#10 Move ko-KR/.gitbook.yaml to ./.gitbook.yaml
  .gitbook.yaml
Labels: enhancement

#12 config/gitbook -> drafts
  .gitbook.yaml
Labels: enhancement

#16 add ko-KR/book.json
  ko-KR/book.json
Labels: documentation

#19 master-ko -> drafts
  ko-KR/book.json
  ko-KR/red-green-blue-gophers-smaller.png
  ko-KR/red-green-blue-gophers.png
Labels: bug

#20 Revert " add ko-KR/book.json"
  ko-KR/book.json
Labels: bug

#21 Add document's structue
  .gitbook.yaml
Labels: enhancement

#24 add contribution instruction for Korean translation
  ko-KR/contributing.md
Labels: documentation

#25 Draft/hello world
  ko-KR/hello-world.md
Labels: enhancement

#43 Draft/array and slices
  ko-KR/arrays-and-slices.md
Labels: enhancement

#45 Translate # Integers
  ko-KR/integers.md
Labels: enhancement

#46 Draft/array and slices
  ko-KR/arrays-and-slices.md
Labels: enhancement

#47 Draft/array and slices
  ko-KR/arrays-and-slices.md
Labels: enhancement
